### ISSUE TITLE
lsm6dsox does not build when optimization level is O2

### ISSUE THREAD

**Issue by idea--list** [STMicroelectronics/lsm6dsox-pid#4]
### Device part numbers

lsm6dsox, not sure about other sensors

### Type of bug

Build error.

### Describe the bug

Project does not build if compiler optimization level is O2.

### Additional context

I integrated the driver into an ESP-IDF project of mine. The project builds fine if optimization level is Og, but fails to build when trying to build at level O2.

![image](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/assets/5784071/63b78e19-5c46-464b-a33f-a89c7275071a)

**Comment by avisconti** [comment]
Can you fetch latest commit (ced3906) and re-test?
I'm closing issue, but you may re-open it if something is still wrong...

**Comment by idea--list** [comment]
@avisconti 
The commit you linked builds and links now as expected.
